"""empty message

Revision ID: 6adac41c22df
Revises: 0bb2b72fa417
Create Date: 2026-02-13 22:37:09.144362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6adac41c22df'
down_revision = '0bb2b72fa417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mass',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('birth_year',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gravity', sa.String(length=120), nullable=True))
        batch_op.alter_column('rotation_period',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('orbital_period',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('diameter',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('surface_water',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('gavity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gavity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('surface_water',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('orbital_period',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rotation_period',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('gravity')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('birth_year',
               existing_type=sa.String(length=30),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('mass',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('favorite_people', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
